-- Native calendar compatibility with verified Acuity configuration, 2026-10-09.
-- Apply after supabase-booking.sql and before enabling the native calendar.
-- Refresh imported Acuity rows before cutover: they now preserve actual source
-- duration and padding. In particular, finalization meetings are 60 minutes.
-- Wedding calendars remain conservatively pooled under wedding-call until
-- staff/resource ownership is verified; this migration invents no extra staff.
-- Acuity service blocks must NOT be imported onto spa classes: Acuity blocks
-- do not affect explicit group classes. Native admin spa closures do apply.
begin;

alter table bookings add column if not exists padding_before_min integer not null default 0
  check (padding_before_min >= 0);
alter table bookings add column if not exists padding_after_min integer not null default 0
  check (padding_after_min >= 0);
update bookings set padding_before_min = 5, padding_after_min = 15
  where product_slug = 'wedding-call' and source in ('native', 'admin');

create table if not exists booking_timed_blackouts (
  id bigint generated by default as identity primary key,
  kind text not null default 'closure' check (kind in ('wedding', 'closure', 'private_event')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  product_slugs text[] not null,
  note text,
  source text not null default 'admin',
  acuity_block_id bigint unique,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at),
  check (cardinality(product_slugs) > 0
    and product_slugs <@ array['farm-tour', 'nordic-spa', 'wedding-call']::text[]
    and array_position(product_slugs, null) is null)
);
create index if not exists booking_timed_blackouts_interval_idx
  on booking_timed_blackouts(starts_at, ends_at);
create index if not exists booking_timed_blackouts_products_idx
  on booking_timed_blackouts using gin(product_slugs);
alter table booking_timed_blackouts enable row level security;
revoke all on booking_timed_blackouts from public, anon, authenticated;
grant select, insert, update, delete on booking_timed_blackouts to service_role;
revoke all on sequence booking_timed_blackouts_id_seq from public, anon, authenticated;
grant usage, select on sequence booking_timed_blackouts_id_seq to service_role;

-- Same public RPC signature and result as the legacy claim, so Square, Stripe
-- and manual booking retain their transactional reservation/gift behavior.
-- Padding, duration, party units and the tour daily cap are server constants;
-- optional client/snapshot JSON fields cannot weaken them. Capacity is the
-- server's validated schedule capacity, bounded by the known product maximum.
create or replace function claim_booking_slots(legs jsonb, booking jsonb)
returns uuid[] language plpgsql security definer set search_path = public
as $$
declare
  leg record;
  lock_row record;
  used integer;
  daily_used integer;
  duration integer;
  pad_before integer;
  pad_after integer;
  requested_units integer;
  capacity integer;
  interval_start timestamptz;
  interval_end timestamptz;
  local_date date;
  new_id uuid;
  ids uuid[] := '{}';
  grp uuid;
begin
  if jsonb_typeof(legs) is distinct from 'array' or jsonb_array_length(legs) not between 1 and 2 then
    raise exception 'one or two booking legs required' using errcode = 'P0002';
  end if;
  if exists (select 1 from jsonb_array_elements(legs) e
    where e ->> 'product_slug' is null
      or e ->> 'product_slug' not in ('farm-tour', 'nordic-spa', 'wedding-call')
      or e ->> 'starts_at' is null) then
    raise exception 'malformed booking leg' using errcode = 'P0002';
  end if;
  -- Lock ALL buffered product/day ranges before any inserts. Different starts
  -- can overlap, and midnight buffers can span days. Shared affected-day locks
  -- close both races; stable global ordering also protects opposite-order combos.
  for lock_row in
    with offered as (
      select e ->> 'product_slug' product_slug, (e ->> 'starts_at')::timestamptz starts_at,
        case e ->> 'product_slug' when 'farm-tour' then 60 when 'nordic-spa' then 90 else 45 end duration,
        case when e ->> 'product_slug' = 'wedding-call' then 5 else 0 end pad_before,
        case when e ->> 'product_slug' = 'wedding-call' then 15 else 0 end pad_after
      from jsonb_array_elements(legs) e
    )
    select distinct o.product_slug, day::date local_day from offered o
      cross join lateral generate_series(
        (((o.starts_at - make_interval(mins => o.pad_before)) at time zone 'America/Los_Angeles')::date)::timestamp,
        (((o.starts_at + make_interval(mins => o.duration + o.pad_after) - interval '1 microsecond')
          at time zone 'America/Los_Angeles')::date)::timestamp,
        interval '1 day'
      ) day
      order by 1, 2
  loop
    perform pg_advisory_xact_lock(hashtextextended('booking-day:' || lock_row.product_slug || '|' || lock_row.local_day::text, 0));
  end loop;
  if jsonb_array_length(legs) > 1 then grp := gen_random_uuid(); end if;

  for leg in select e ->> 'product_slug' product_slug,
    (e ->> 'starts_at')::timestamptz starts_at, (e ->> 'capacity')::integer offered_capacity,
    (e ->> 'party_size')::integer party_size, (e ->> 'amount_cents')::integer amount_cents
    from jsonb_array_elements(legs) e order by 1, 2
  loop
    if leg.offered_capacity is null or leg.offered_capacity <= 0
      or leg.party_size is null or leg.party_size < (case when leg.product_slug = 'farm-tour' then 2 else 1 end)
      or leg.party_size > (case when leg.product_slug = 'wedding-call' then 2 else 6 end)
      or leg.amount_cents is null or leg.amount_cents < 0 then
      raise exception 'malformed booking leg' using errcode = 'P0002';
    end if;
    duration := case leg.product_slug when 'farm-tour' then 60 when 'nordic-spa' then 90 else 45 end;
    pad_before := case when leg.product_slug = 'wedding-call' then 5 else 0 end;
    pad_after := case when leg.product_slug = 'wedding-call' then 15 else 0 end;
    requested_units := case when leg.product_slug = 'nordic-spa' then leg.party_size else 1 end;
    capacity := least(leg.offered_capacity, case leg.product_slug when 'wedding-call' then 1 when 'farm-tour' then 2 else 6 end);
    interval_start := leg.starts_at - make_interval(mins => pad_before);
    interval_end := leg.starts_at + make_interval(mins => duration + pad_after);
    local_date := (leg.starts_at at time zone 'America/Los_Angeles')::date;

    if exists (select 1 from booking_timed_blackouts b
      where b.product_slugs @> array[leg.product_slug]
        and b.starts_at < interval_end and b.ends_at > interval_start)
      or exists (select 1 from booking_blackouts b
        where b.product_slugs @> array[leg.product_slug]
          and b.starts_on::timestamp at time zone 'America/Los_Angeles' < interval_end
          and (b.ends_on + 1)::timestamp at time zone 'America/Los_Angeles' > interval_start) then
      raise exception 'slot blocked for % at %', leg.product_slug, leg.starts_at using errcode = 'P0001';
    end if;
    if leg.product_slug = 'farm-tour' then
      select count(*) into daily_used from bookings b
        where b.product_slug = leg.product_slug
          and b.starts_at >= local_date::timestamp at time zone 'America/Los_Angeles'
          and b.starts_at < (local_date + 1)::timestamp at time zone 'America/Los_Angeles'
          and (b.status in ('confirmed', 'completed', 'no_show')
            or (b.status = 'pending' and b.hold_expires_at > now()));
      if daily_used >= 6 then
        raise exception 'daily appointment limit reached for % on %', leg.product_slug, local_date using errcode = 'P0001';
      end if;
    end if;
    if leg.product_slug = 'nordic-spa' then
      -- Independent explicit classes retain their own seats even when their
      -- durations overlap. Native admin timed closures above still apply.
      select coalesce(sum(b.units), 0) into used from bookings b
        where b.product_slug = leg.product_slug and b.starts_at = leg.starts_at
          and (b.status = 'confirmed' or (b.status = 'pending' and b.hold_expires_at > now()));
    else
    with busy as (
      select greatest(interval_start, b.starts_at - make_interval(mins => b.padding_before_min)) lo,
        least(interval_end, b.starts_at + make_interval(mins => b.duration_min + b.padding_after_min)) hi, b.units
        from bookings b where b.product_slug = leg.product_slug
          and (b.status = 'confirmed' or (b.status = 'pending' and b.hold_expires_at > now()))
          and b.starts_at - make_interval(mins => b.padding_before_min) < interval_end
          and b.starts_at + make_interval(mins => b.duration_min + b.padding_after_min) > interval_start
    ), events as (
      select lo t, units delta from busy union all select hi, -units from busy
    ), deltas as (select t, sum(delta) delta from events group by t),
    totals as (select sum(delta) over (order by t) occupied from deltas)
    select coalesce(max(occupied), 0) into used from totals;
    end if;
    if used + requested_units > capacity then
      raise exception 'slot full for % at % (used %, capacity %)', leg.product_slug, leg.starts_at, used, capacity using errcode = 'P0001';
    end if;
    insert into bookings (
      booking_number, product_slug, starts_at, duration_min, padding_before_min, padding_after_min,
      party_size, units, status, hold_expires_at, combo_group,
      first_name, last_name, email, phone, amount_cents,
      referral_source, policy_agreed_at, location_choice, source
    ) values (
      (booking ->> 'booking_number') || case when grp is null then '' else '-' || (cardinality(ids) + 1)::text end,
      leg.product_slug, leg.starts_at, duration, pad_before, pad_after,
      leg.party_size, requested_units, 'pending', now() + interval '10 minutes', grp,
      booking ->> 'first_name', booking ->> 'last_name', booking ->> 'email', booking ->> 'phone', leg.amount_cents,
      booking ->> 'referral_source', nullif(booking ->> 'policy_agreed_at', '')::timestamptz,
      nullif(booking ->> 'location_choice', ''), coalesce(booking ->> 'source', 'native')
    ) returning id into new_id;
    ids := ids || new_id;
  end loop;
  return ids;
end;
$$;
revoke all on function claim_booking_slots(jsonb, jsonb) from public, anon, authenticated;
grant execute on function claim_booking_slots(jsonb, jsonb) to service_role;
commit;
